### ISSUE TITLE
Multiple commands to execute

### ISSUE THREAD

**Issue by jakecjones** [adaltas/node-ssh2-exec#7]
return connect({
            host: '111.11.11.11',
            username: 'user',
            password: 'password'
          }, (err, ssh) => {

            fs.writeFile(ssh, '/Users/path/to/folder/textfile.txt, codeToWrite, (err) => {
              if (err) throw err;
              console.log('Saved!');

              // execute promise

              return exec('ls; pwd' {ssh: ssh}, (err, stdout, stderr) => {
                console.log(stdout);
                console.log(err);
              });

            })

            console.log(err);
    

Currently I can execute one command easily under the **// execute promise** but I want to execute two, Am I missing something? ls and pwd just represent different commands. 

This is being run on firebase functions.  I am pretty new to all of this.

**Comment by wdavidw** [comment]
You mean executing 2 commands like pwd and ls? It’s perfectly valid, I do it all the time.

**Comment by jakecjones** [comment]
You are correct, I had a server error and not a code error.

**Comment by jakecjones** [comment]
Any idea how I would execute another command in the promise?

**Comment by wdavidw** [comment]
There is currently no native API for promise. Not that it doesn't make sense, I just didn't need it but it could be added. Nothing prevents you from chaining multiple calls, this is what we do with [nikita](https://nikita.js.org/), here's an example:

```js
require('nikita')
.ssh.open({
  host: 'localhost'
})
.system.execute("mycommand -step 1)
.system.execute("mycommand --step 2")
.ssh.close()
.next(function(err){
  console.log(err ? err.message : 'ok')
})
```

**Comment by jakecjones** [comment]
I'll give it a try! Thanks so much. :)
